apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    component: backend
spec:
  selector:
    matchLabels:
      app: mysql
      component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      containers:
      - name: mysql-db
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pass123  # Replace with your desired MySQL root password
          - name: MYSQL_DATABASE
            value: employees
        ports:
        - containerPort: 3306
          protocol: TCP
