apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    component: backend
spec:
  selector:
    matchLabels:
      app: mysql
      component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      serviceAccountName: clo835-group11  # Assign the created ServiceAccount
      containers:
      - name: mysql-db
        image: mysql:latest
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-database
       
        ports:
        - containerPort: 3306
          protocol: TCP
