apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: final
spec:
  storageClassName: gp3  # Specify the storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Specify the desired storage size

      
